### PR TITLE
Added CocoaPods podspec file

### PR DESCRIPTION
**Pull request by ehlersd**
Signed-off-by: Darren Ehlers me@darrenehlers.com

### CODE REVIEW

**Comment by jberlana** [comment]
Thanks Darren!

I didn't add the podspect because is not a Library, is more like a code snippet. But, anyways is good to have it.

**Comment by esttorhe** [comment]
@jberlana the `podspec` was added but was never submitted to the `CocoaPods` specs (I can't find it running `pod search JBParallaxCell`).

Are you planning on publishing it via `CocoaPods` or no?

Thanks.

**Comment by jberlana** [comment]
Just send the pod to `CocoaPods` via trunk API, this is the commit https://github.com/CocoaPods/Specs/commit/8d32fdd79648dd9583d953b5b48171afcc33a21d

**Comment by esttorhe** [comment]
Awesome!

Thanks

**Pull request merged**
